version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "80:80"
    restart: always
