version: '3'
services:
  bot:
    build:
      context: .
      target: bot
    ports:
      - "5000:5000"
    depends_on:
      - web

  web:
    build:
      context: .
      target: web
    ports:
      - "80:80"
